/*
 * action types
 */

module.exports = {
    DELETE_USER: 'DELETE_USER',
    EDIT_USER: 'EDIT_USER',
    SET_SEARCH_USERS: 'SET_SEARCH_USERS',
    SET_ADMIN_USER: 'SET_ADMIN_USER',
    SET_SEARCH_LOCATIONS: 'SET_SEARCH_LOCATIONS',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER'
};
