/*
 * action types
 */

module.exports = {
    DELETE_USER: 'DELETE_USER',
    EDIT_USER: 'EDIT_USER',
    SET_SEARCH_USERS: 'SET_SEARCH_USERS',
    SET_ADMIN_USER: 'SET_ADMIN_USER',
    SET_STORE_EMPLOYEES: 'SET_STORE_EMPLOYEES',
    SET_SEARCH_LOCATIONS: 'SET_SEARCH_LOCATIONS',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',
    SET_ACTIVE_USER_LATEST_CONTENTS: 'SET_ACTIVE_USER_LATEST_CONTENTS',
    SET_CHANNEL_FOR_USER: 'SET_CHANNEL_FOR_USER'
};
