development:
  adapter: postgresql
  encoding: unicode
  database: expresso_development
  host: localhost
  pool: 5
  username: daniel
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: expresso_test
  pool: 5
  username: daniel
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: expresso_production
  pool: 5
  host: localhost
  username: barista
  password: c3chensi

staging:
  adapter: postgresql
  encoding: unicode
  database: expresso_production
  pool: 5
  host: localhost
  username: barista
  password: c3chensi
