development:
  adapter: postgresql
  encoding: unicode
  database: expresso_development
  host: localhost
  pool: 5
  username: daniel
  password: c3chensi

test:
  adapter: postgresql
  encoding: unicode
  database: expresso_test
  host: main-database.cx04pnrh1sfk.us-west-2.rds.amazonaws.com
  port: 5432
  pool: 5
  username: barista
  password: c3chensi

staging:
  adapter: postgresql
  encoding: unicode
  database: expresso_test
  host: main-database.cx04pnrh1sfk.us-west-2.rds.amazonaws.com
  port: 5432
  pool: 5
  username: barista
  password: c3chensi

production:
  adapter: postgresql
  encoding: unicode
  database: expresso_test
  host: main-database.cx04pnrh1sfk.us-west-2.rds.amazonaws.com
  port: 5432
  pool: 5
  username: barista
  password: c3chensi
