backupt:
  adapter: postgresql
  encoding: unicode
  database: expresso_development
  host: localhost
  port: 5432
  pool: 5
  username: daniel
  password: c3chensi

backupp:
  adapter: postgresql
  encoding: unicode
  database: expresso_production
  host: database-server.cx04pnrh1sfk.us-west-2.rds.amazonaws.com
  port: 5432
  pool: 5
  username: manager
  password: 6P;Jz6Kju^2(

development:
  adapter: postgresql
  encoding: unicode
  database: expresso_test
  host: database-server.cx04pnrh1sfk.us-west-2.rds.amazonaws.com
  port: 5432
  pool: 5
  username: barista
  password: 7Bx6+~!1gQbN

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  host: <%= ENV['RDS_HOST_NAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 10
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>

staging:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  host: <%= ENV['RDS_HOST_NAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 10
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  host: <%= ENV['RDS_HOST_NAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 10
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
