# This file contains environment variables and any string externalizations

messages:
  status:
    1: Success
    100: Verifying email address that already exists
    103: Continue page error
    104: Invitation invited setup new users error
    105: Invitation whitelist setup new users error
    106: Invitation general setup new users error
    107: Cannot find invitation object doing invitation setup
    108: Reset password failed
    109: Change password failed
    125: Invitation dashboard update failed
    126: User dashboard update failed
    127: User dashboard bulk update failed
    128: User admin status failed to update
    129: Organization secure network update failed
    130: Organization profanity filter update failed
    131: Post sorted_at date update failed
    132: Twilio callback failed
    135: Failed to send invitation email
    139: PDF upload failed
    151: Shift is un-available for cover (deleted)
    152: Shift is un-available for cover (already covered)
    185: urls_controller error update
    186: schedule_elements cover error
    187: schedule_elements uncover error
  menu:
    tab1: Dashboard
    tab2: Announcements
    tab3: Training
    tab4: Quizzes
    tab5: Reports
    tab6: Users
    tab7: Groups
    tab8: Locations
    tab9: Settings
  footer:
    year: 2015
    company_name: Coffee Software Design Inc.
    version: 3.4
    build: 4
  menu1:
    title: Network Activity
    boxText1: Chat Messages
    boxText2: Newsfeed Posts
    boxText3: Likes
    boxText4: Active Users
    filter1: Last 24 Hour
    filter2: Last 48 Hour
    filter3: Week
    filter4: Month
    filter5: All Time
  menu2:
    title: Feeds
    caption: create social engagement in your workplace
    buttonText: New
    table1Col1: Announcements
    table1Col2: Group
    table1Col3: Location
    table1Col4: Create Date
    table2Col1: NewsFeeds
    table2Col2: Author
    table2Col3: Date
    modalTitle: New Announcement
    modalCheckbox: Push Notification
    modalHint1: Location
    modalHint2: User Group
    modalIEText1: Location
    modalIEText2: Group
    modalIEText3: Announcement Title
    modalIEText4: Announcement Content
    modalPlaceholderText1: Announcement Title (140 characters max)
    modalPlaceholderText2: Announcement Content
    modalButtonText1: Preview
    modalButtonText2: Submit
    modalButtonText3: Close
    footerMessage: Click on an announcement in the table above to see its statistics
  menu3:
    title: Training
    caption: improve employee performance
    buttonText: New
    table1Col1: Custom Trainings
    table1Col2: Type
    table1Col3: Group
    table1Col4: Location
    table1Col5: Date
    table2Col1: Safety Trainings
    table2Col2: Availability
    table2Col3: Enable
    # --- MODAL 1 START --- #
    modal1Title: Upload Training Type
    modal1subtitle1: Youtube
    modal1subtitle2: Video
    modal1subtitle3: PDF
    modal1subtitle4: Word
    modal1subtitle5: Excel
    modal1subtitle6: Powerpoint
    modal1ButtonText1: Close
    # --- MODAL 1 END --- #
    # --- MODAL 2 START --- #
    modal2Title: New Youtube Training
    modal2Checkbox: Push Notification
    modal2Hint1: Location
    modal2IEText1: Group
    modal2IEText2: Youtube Training Title
    modal2IEText3: Youtube URL
    modal2IEText4: Location
    modal2Hint2: User Group
    modal2PlaceholderText1: Training Title (140 characters max)
    modal2PlaceholderText2: Youtube URL
    modal2subtitle1: Title
    modal2subtitle2: Duration
    modal2ButtonText1: Preview
    modal2ButtonText2: Submit
    modal2ButtonText3: Close
    # --- MODAL 2 END --- #
    # --- MODAL 3 START --- #
    modal3Title: New Video Training
    modal3Hint1: Location
    modal3Hint2: User Group
    modal3IEText1: Location
    modal3Hint1: Location
    modal3IEText2: Group
    modal3Hint2: User Group
    modal3IEText3: Video Training Title
    modal3PlaceholderText1: Video Training Title (140 characters max)
    modal3ButtonText1: Submit
    modal3ButtonText2: Close
    # --- MODAL 3 END --- #
    # --- MODAL 4 START --- #
    modal4Title: New Word Document Training
    modal4Checkbox: Make an announcement about this training
    modal4IEText1: Location
    modal4Hint1: Location
    modal4IEText2: Group
    modal4Hint2: User Group
    modal4IEText3: Word Document Training Title
    modal4PlaceholderText1: Word Document Training Title (140 characters max)
    modal4ButtonText1: Submit
    modal4ButtonText2: Close
    # --- MODAL 4 END --- #
    # --- MODAL 5 START --- #
    modal5Title: New Excel Document Training
    modal5Checkbox: Make an announcement about this training
    modal5IEText1: Location
    modal5Hint1: Location
    modal5IEText2: Group
    modal5Hint2: User Group
    modal5IEText3: Excel Document Training Title
    modal5PlaceholderText1: Excel Document Training Title (140 characters max)
    modal5ButtonText1: Submit
    modal5ButtonText2: Close
    # --- MODAL 5 END --- #
    # --- MODAL 6 START --- #
    modal6Title: New Powerpoint Training
    modal6Checkbox: Make an announcement about this training
    modal6IEText1: Location
    modal6Hint1: Location
    modal6IEText2: Group
    modal6Hint2: User Group
    modal6IEText3: Powerpoint Training Title
    modal6PlaceholderText1: Powerpoint Training Title (140 characters max)
    modal6ButtonText1: Submit
    modal6ButtonText2: Close
    # --- MODAL 6 END --- #
    # --- MODAL 7 START --- #
    modal7Title: New PDF Training
    modal7Checkbox: Make an announcement about this training
    modal7IEText1: Location
    modal7Hint1: Location
    modal7IEText2: Group
    modal7Hint2: User Group
    modal7IEText3: PDF Training Title
    modal7PlaceholderText1: PDF Training Title (140 characters max)
    modal7ButtonText1: Submit
    modal7ButtonText2: Close
    # --- MODAL 7 END --- #
    # --- MODAL 8 START --- #
    modal8Title: "Are You Sure?"
    modal8Text1: This action would not be reversible and statistics associated with this training will be lost
    modal8ButtonText1: Confirm
    modal8ButtonText2: Close
    # --- MODAL 8 END --- #
    # --- MODAL 9 START --- #
    modal9Title: "Sorry!"
    modal9Text1: "We could not verify this Youtube link..."
    modal9ButtonText1: Okay
    # --- MODAL 9 END --- #
    # --- MODAL 10 START --- #
    modal10Title: Sorry
    modal10Text1: "The video is still processing, try again later..."
    modal10ButtonText1: Okay
    # --- MODAL 10 END --- #
    # --- MODAL 11 START --- #
    modal11Title: "Processing..."
    modal11Text1: "The video will take about 10 to 30 minutes to process, it will show up in your Coffee Mobile network and the dashboard once it is processed."
    modal11ButtonText1: Okay
    # --- MODAL 11 END --- #
    # --- MODAL 12 START --- #
    modal12Title: Training Preview
    modal12ButtonText1: Close
    # --- MODAL 12 END --- #
    footerMessage: Click on a training in the tables above to see its statistics
  menu4:
    title: Quizzes
    caption: "test your employees"
    buttonText: New
    footerMessage: "Click on a quiz in the table above to see its statistics"
    table1Col1: Custom Quizzes
    table1Col2: Questions
    table1Col3: Time Limit
    table1Col4: Pass Mark
    table1Col5: Group
    table1Col6: Location
    table1Col7: Create Date
    # --- MODAL 1 START --- #
    modal1Title: Create Quiz Type
    modal1subtitle1: Safety
    modal1subtitle2: Training
    modal1ButtonText1: Close
    # --- MODAL 1 END --- #
    # --- MODAL 2 START --- #
    modal2Title: New Quiz
    modal2Checkbox: Push Notification
    modal2IEText1: Quiz Name
    modal2PlaceholderText1: Quiz Name (140 characters max)
    modal2IEText2: Location
    modal2Hint1: Location
    modal2IEText3: Time Limit
    modal2Hint2: Time Limit
    modal2IEText4: Group
    modal2Hint3: User Group
    modal2IEText5: Pass Mark
    modal2Hint4: Pass Mark
    modal2ButtonText1: Preview
    modal2ButtonText2: Submit
    modal2ButtonText3: Close
    modal2ButtonText4: "Add Question +"
    # --- MODAL 2 END --- #
    # --- MODAL 3 START --- #
    modal3Title: Add Question
    modal3IEText1: "Question (100 characters max)"
    modal3PlaceholderText1: "Question (100 characters max)"
    modal3IEText2: "Correct Answer"
    modal3PlaceholderText2: "Correct Answer (option 1)"
    modal3IEText3: Answer
    modal3PlaceholderText3: Answer (option 2)
    modal3IEText4: Answer
    modal3PlaceholderText4: Answer (option 3)
    modal3IEText5: Answer
    modal3PlaceholderText5: Answer (option 4)
    modal3OptionText1: Randomize answers
    modal3ButtonText1: Preview
    modal3ButtonText2: Add Question
    modal3ButtonText3: Close
    # --- MODAL 3 END --- #
    # --- MODAL 4 START --- #
    modal4Title: "Are You Sure?"
    modal4Text1: "This action would not be reversible and statistics associated with this quiz will be lost."
    modal4ButtonText1: Confirm
    modal4ButtonText2: Close
    # --- MODAL 4 END --- #
    # --- MODAL 5 START --- #
    modal5Title: Question Preview
    modal5ButtonText1: Close
    # --- MODAL 5 END --- #
    # --- MODAL 6 START --- #
    modal6Title: Quiz Preview
    modal6ButtonText1: Previous
    modal6ButtonText2: Next
    modal6ButtonText3: Close
    # --- MODAL 6 END --- #
    # --- MODAL 7 START --- #
    modal7Title: Quiz Preview
    modal7Text1: "The quiz does not have any questions right now. It must have at least one question before it can be previewed."
    modal7ButtonText1: Okay
    # --- MODAL 7 END --- #
    # --- MODAL 8 START --- #
    modal8Title: Confirmation
    modal8Text1: "The quiz have question(s) in it right now. Closing it means you will lose the question data, are you sure?"
    modal8ButtonText1: "Yes, I'm Done."
    modal8ButtonText2: Nevermind
    # --- MODAL 8 END --- #
    # --- MODAL 9 START --- #
    modal9Title: Confirmation
    modal9Text1: "Are you sure you want to close the quiz creation window? Your progress will not be saved."
    modal9ButtonText1: "Yes, close it"
    modal9ButtonText2: "No, I'm not done yet"
    # --- MODAL 9 END --- #
  menu5:
    table1Col1: Report By Quiz
    table1Col2: Group
    table1Col3: Location
    table2Col1: Report By User
    table2Col2: Group
    table2Col3: Location
    footerMessage: "Click on a quiz or a user in the table above to see its report"
    # --- MODAL 1 START --- #
    modal1Title: Quiz Playback
    modal1ButtonText1: Previous
    modal1ButtonText2: Next
    modal1ButtonText3: Close
    # --- MODAL 1 END --- #
    # --- MODAL 2 START --- #
    modal2Title: Quiz Preview
    modal2Text1: "There is no questions in the quiz right now, you need at least 1 question in the quiz to preview it."
    modal2ButtonText1: Okay
    # --- MODAL 2 END --- #
    # --- MODAL 3 START --- #
    modal3Title: "Oops! Something's Wrong"
    modal3Text1: "Sorry, we were not able to replay this quiz at the moment."
    modal3ButtonText1: Okay
    # --- MODAL 3 END --- #
    # --- MODAL 4 START --- #
    modal4Title: "Advanced Quiz Report (user view)"
    table3Col1: User
    table3Col2: Date
    table3Col3: Location
    table3Col4: Group
    table3Col5: Score
    table3Col6: Status
    table3Col7: Replay
    modal4ButtonText2: Close
    # --- MODAL 4 END --- #
    # --- MODAL 5 START --- #
    modal5Title: "Advanced Quiz Report (question view)"
    boxMessage1: Reached
    boxDetail1: "The percentage of users that got to this question during their quiz attempt."
    boxMessage2: "Avg. Time"
    boxDetail2: "The average time it took for users to complete the question (if the data is available)."
    boxMessage3: Share
    modal5ButtonText1: Previous
    modal5ButtonText2: Next
    modal5ButtonText3: Close
    # --- MODAL 5 END --- #
    table4Title: Compliance
    table4Col1: Quiz
    table4Col2: High Score
    table4Col3: Posted
    table4Col4: Completed
    table4Col5: Passed
    table4Col6: Attempts
  menu6:
    tabTitle1: Users
    tabTitle2: Invitations
    tabTitle3: Deactivated Users
    table1Col1: Name
    table1Col2: Email
    table1Col3: Phone
    table1Col4: Group
    table1Col5: Location
    table1Col6: Location Name
    table1Col7: Status
    buttonMenuText1: New
    buttonMenuText2: Bulk Actions
    buttonMenuText3: Edit
    buttonMenuText4: Ban
    buttonMenuText5: New
    buttonMenuText6: Bulk Actions
    buttonMenuText7: Edit
    buttonMenuText8: Ban
    table3Col1: Name
    table3Col2: Invited On
    table3Col3: Email
    table3Col4: Phone
    table3Col5: Group
    table3Col6: Location
    table3Col7: Actions
    table4Col1: Name
    table4Col2: Email
    table4Col3: Phone
    table4Col4: Group
    table4Col5: Location
    table4Col6: Status
    # --- MODAL 1 START --- #
    modal1Title: User Entry Method
    modal1subtitle1: Manual Entry
    modal1subtitle2: Excel Upload
    modal1ButtonText1: Close
    # --- MODAL 1 END --- #
    # --- MODAL 2 START --- #
    modal2Title: User Entry
    modal2IEText1: First Name
    modal2PlaceholderText1: First Name
    modal2IEText2: Last Name
    modal2PlaceholderText2: Last Name
    modal2IEText3: Email
    modal2PlaceholderText3: Email
    modal2IEText4: Phone
    modal2PlaceholderText4: Phone Number
    modal2IEText5: Location
    modal2IEText6: Group 
    modal2ButtonText1: Submit
    modal2ButtonText2: Close
    # --- MODAL 2 END --- #
    # --- MODAL 3 START --- #
    modal3Title: "Import Users From File"
    modal3InfoMessage1: Download the Template
    modal3InfoMessage2: "NOTE:"
    modal3InfoMessage3: "This plugins works only on Latest Chrome, Firefox, Safari, Opera & Internet Explorer 10."
    modal3ButtonText1: Close
    # --- MODAL 3 END --- #
    # --- MODAL 4 START --- #
    modal4Title: Mass User Invitation
    table2Col1: Name
    table2Col2: Email
    table2Col3: Phone
    table2Col4: Actions
    modal4Text1: "0"
    modal4Text2: "%"
    modal4Text3: "Complete"
    modal4ButtonText1: Submit
    modal4ButtonText2: Close
    # --- MODAL 4 END --- #
    # --- MODAL 5 START --- #
    modal5Title: Unit Number
    modal5PlaceholderText1: Unit Number
    modal5ButtonText1: Add
    modal5ButtonText2: Close
    # --- MODAL 5 END --- #
    # --- MODAL 6 START --- #
    modal6Title: User
    modal6ButtonText1: Close
    # --- MODAL 6 END --- #
    # --- MODAL 7 START --- #
    modal7Title: Edit Users
    modal7subtitle1: User List
    modal7subtitle2: Location
    modal7subtitle3: User Group
    modal7ButtonText1: Close
    # --- MODAL 7 END --- #
    # --- MODAL 8 START --- #
    modal8Title: Edit Invitees
    modal8subtitle1: User List
    modal8subtitle2: Location
    modal8subtitle3: User Group
    modal8ButtonText1: Close
    # --- MODAL 8 END --- #
    # --- MODAL 9 START --- #
    modal9Title: Invitation
    modal9ButtonText1: Close
    # --- MODAL 9 END --- #
    # --- MODAL 10 START --- #
    modal10Title: Applicant
    modal10ButtonText1: Close
    # --- MODAL 10 END --- #
    # --- MODAL 11 START --- #
    modal11Title: Bulk Edit
    modal11InfoMessage1: "You must make at least one selection before bulk editing."
    modal11ButtonText1: Okay
    # --- MODAL 11 END --- #
    # --- MODAL 12 START --- #
    modal12Title: Bulk Delete
    modal12InfoMessage1: "You must make at least one selection before bulk deleting."
    modal12ButtonText1: Okay
    # --- MODAL 12 END --- #
  menu7:
    tabTitle1: Groups
    table1Col1: Name
    table1Col2: Description
    table1Col3: Members
    buttonMenuText1: New
    # --- MODAL 1 START --- #
    modal1Title: New Group
    modal1InfoMessage1: "NOTE:"
    modal1InfoMessage2: "This plugins works only on Latest Chrome, Firefox, Safari, Opera & Internet Explorer 10."
    modal1IEText1: Group Name
    modal1PlaceholderText1: Group Name
    modal1IEText2: Group Description
    modal1PlaceholderText2: Group Description
    modal1ButtonText1: Submit
    modal1ButtonText2: Close
    # --- MODAL 1 END --- #
  menu8:
    tabTitle1: Locations
    table1Col1: Name
    table1Col2: Address
    table1Col3: Members
    buttonMenuText1: New
    # --- MODAL 1 START --- #
    modal1Title: New Location
    modal1IEText1: Location Address
    modal1PlaceholderText1: "Location Address"
    modal1IEText2: Location Name
    modal1PlaceholderText2: Location Name
    modal1Text1: "+ Unit number?"
    modal1Hint1: "Enter your location name or address, select from the dropdown to locate."
    modal1ButtonText1: Submit
    modal1ButtonText2: Close
    # --- MODAL 1 END --- #
  menu9:
    tabTitle1: Network
    settingName1: Profanity
    switchEnabledText1: Enabled
    switchDisabledText1: Disabled
    settingName2: Secure Network
    switchEnabledText2: Enabled
    switchDisabledText2: Disabled

