development:
  host: 'localhost'
  port: '6379'
test:
  host: 'redis-ec.bsvzz7.ng.0001.usw2.cache.amazonaws.com:'
  port: '6379'
production:
  host: 'redis-ec.bsvzz7.ng.0001.usw2.cache.amazonaws.com'
  port: '6379'
