development:
  bucket: coffeemobile
  access_key_id: AKIAJFAUZ4Y22BP2XOTA
  secret_access_key: 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

test:
  bucket: coffeemobile
  access_key_id: AKIAJFAUZ4Y22BP2XOTA
  secret_access_key: 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

production:
  bucket: coffeemobile
  access_key_id: AKIAJFAUZ4Y22BP2XOTA
  secret_access_key: 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
  
staging:
  bucket: coffeemobile_staging 
  access_key_id: AKIAJFAUZ4Y22BP2XOTA
  secret_access_key: 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