# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:logfile: /var/log/sidekiq.log
:pidfile: /var/app/support/pids/sidekiq.pid
:verbose: false
:concurrency:  4
:daemon: true
:queues:
  - [high, 9]
  - [often, 7]
  - [default, 5]
  - [seldom, 3]
