s3_input:
  bucket: coffeemobile_development
  access_key_id: AKIAJFAUZ4Y22BP2XOTA
  secret_access_key: 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
s3_output:
  bucket: coffeemobile_encoded
  access_key_id: AKIAJFAUZ4Y22BP2XOTA
  secret_access_key: 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
settings:
  notification_url: http://dashboard.coffeemobile.com/api/videos/zencoder_callback