'use strict';exports.__esModule=true;var _extends2=require('babel-runtime/helpers/extends');var _extends3=_interopRequireDefault(_extends2);var _classCallCheck2=require('babel-runtime/helpers/classCallCheck');var _classCallCheck3=_interopRequireDefault(_classCallCheck2);var _possibleConstructorReturn2=require('babel-runtime/helpers/possibleConstructorReturn');var _possibleConstructorReturn3=_interopRequireDefault(_possibleConstructorReturn2);var _inherits2=require('babel-runtime/helpers/inherits');var _inherits3=_interopRequireDefault(_inherits2);var _react=require('react');var _react2=_interopRequireDefault(_react);var _reactRedux=require('react-redux');var _redux=require('redux');var _reactDom=require('react-dom');var _reactDom2=_interopRequireDefault(_reactDom);var _lodash=require('lodash');var _lodash2=_interopRequireDefault(_lodash);var _rubix=require('@sketchpixy/rubix');var _apiUserActions=require('../redux/actions/apiUserActions');var _modalDeleteUser=require('../redux/actions/actionTypes/modalDeleteUser');var _UserDelete=require('../components/UserDelete');var _UserDelete2=_interopRequireDefault(_UserDelete);var _UserListElement=require('../components/UserListElement');var _UserListElement2=_interopRequireDefault(_UserListElement);var _superagent=require('superagent');var _superagent2=_interopRequireDefault(_superagent);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}var DatatableComponent=function(_React$Component){(0,_inherits3.default)(DatatableComponent,_React$Component);function DatatableComponent(){(0,_classCallCheck3.default)(this,DatatableComponent);return(0,_possibleConstructorReturn3.default)(this,_React$Component.apply(this,arguments));}DatatableComponent.prototype.componentDidMount=function componentDidMount(){$(_reactDom2.default.findDOMNode(this.example)).addClass('nowrap');//.dataTable({
//       columnDefs: [
//           { targets: [-1, -3], className: 'dt-body-left' }
//       ],
//   });
};DatatableComponent.prototype.updateSearch=function updateSearch(){this.search(this.refs.searchInput.value);};DatatableComponent.prototype.search=function search(){var _this2=this;var query=arguments.length>0&&arguments[0]!==undefined?arguments[0]:"";if(query!==""){var url='http://localhost:3000/api/users/search?user_name='+query;_superagent2.default.get(url).set({'x-method':'pass_verification','accept':'application/vnd.Expresso.v0','content-type':'application/json'}).then(function(response){_this2.props.getUsers(response.body.eXpresso);});}};DatatableComponent.prototype.render=function render(){var _this3=this;return _react2.default.createElement('div',null,_react2.default.createElement('div',null,_react2.default.createElement('input',{ref:'searchInput',type:'text',id:'serarchBox'}),_react2.default.createElement('button',{id:'serachButton',onClick:function onClick(e){_this3.updateSearch();}},'Search')),_react2.default.createElement(_rubix.Table,{ref:function ref(c){return _this3.example=c;},className:'display',cellSpacing:'0',width:'100%'},_react2.default.createElement('thead',null,_react2.default.createElement('tr',null,_react2.default.createElement('th',null,'Id'),_react2.default.createElement('th',null,'First Name'),_react2.default.createElement('th',null,'Last Name'),_react2.default.createElement('th',null,'Phone Number'),_react2.default.createElement('th',null,'Edit'),_react2.default.createElement('th',null,'Delete'))),_react2.default.createElement('tbody',null,this.props.users.map(function(user,index){return _react2.default.createElement(_UserListElement2.default,{key:user.id,user:user});})),_react2.default.createElement('tfoot',null,_react2.default.createElement('tr',null,_react2.default.createElement('th',null,'Id'),_react2.default.createElement('th',null,'First Name'),_react2.default.createElement('th',null,'Last Name'),_react2.default.createElement('th',null,'Phone Number'),_react2.default.createElement('th',null,'Edit'),_react2.default.createElement('th',null,'Delete')))),_react2.default.createElement(_UserDelete2.default,null));};return DatatableComponent;}(_react2.default.Component);//@connect((state) => state.userReducer)
var UserList=function(_React$Component2){(0,_inherits3.default)(UserList,_React$Component2);function UserList(){(0,_classCallCheck3.default)(this,UserList);return(0,_possibleConstructorReturn3.default)(this,_React$Component2.apply(this,arguments));}UserList.prototype.render=function render(){return _react2.default.createElement(_rubix.Row,null,_react2.default.createElement(_rubix.Col,{xs:12},_react2.default.createElement(_rubix.PanelContainer,null,_react2.default.createElement(_rubix.Panel,null,_react2.default.createElement(_rubix.PanelBody,null,_react2.default.createElement(_rubix.Grid,null,_react2.default.createElement(_rubix.Row,null,_react2.default.createElement(_rubix.Col,{xs:12},_react2.default.createElement(DatatableComponent,this.props),_react2.default.createElement('br',null)))))))));};return UserList;}(_react2.default.Component);var mapStateToProps=function mapStateToProps(state){return{users:state.userReducer.users};};//const mapDispatchToProps = (dispatch) => {
//    return bindActionCreators({
//        selectUser: SelectUser, 
//        modalDelete: ModalDeleteUser,
//    }, dispatch);
//
//};
var myDispatch=function myDispatch(dispatch,props){return(0,_extends3.default)({dispatch:dispatch},(0,_redux.bindActionCreators)({getUsers:_apiUserActions.getUsers},dispatch));};var _default=(0,_reactRedux.connect)(mapStateToProps,myDispatch)(UserList);exports.default=_default;;var _temp=function(){if(typeof __REACT_HOT_LOADER__==='undefined'){return;}__REACT_HOT_LOADER__.register(DatatableComponent,'DatatableComponent','src/routes/UserList.js');__REACT_HOT_LOADER__.register(UserList,'UserList','src/routes/UserList.js');__REACT_HOT_LOADER__.register(mapStateToProps,'mapStateToProps','src/routes/UserList.js');__REACT_HOT_LOADER__.register(myDispatch,'myDispatch','src/routes/UserList.js');__REACT_HOT_LOADER__.register(_default,'default','src/routes/UserList.js');}();;